[project]
name = "yamibo-scraper"
version = "1.4"
description = "A simple tool for yuri lovers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "curl-cffi>=0.14.0",
    "ebooklib>=0.20",
    "opencc-python-reimplemented>=0.1.7",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
]

[project.scripts]
yamibo = "yamibo_scraper:main"
yamibo-gui = "gui_app:launch_gui"
yamibo-cmd = "yamibo_cmd:main"
